#=================================================
# OpenWRT-CI Workflows for Build OpenWRT firmware
# openwrt:LEDE
# package:haiibo
#=================================================

name: Build_OpenWRT

on:
  workflow_dispatch:
    inputs:
      device:
        description: '选择需要编译的设备'     
        required: true
        default: 'Build-x86' 
        type: choice
        options:
        - Build-x86
        - Build-R2S
        - Build-R4S
        - Build-GL.iNET-MT1300
        

      host:
        description: '输入主机名'
        required: true
        default: 'DinG'
        
      ip:
        description: '定义路由器IP'
        required: true
        default: '10.0.0.1'
        
      core:
        description: '是否启用6.1内核'
        required: false
        type: boolean

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  REPO_URL: https://github.com/coolsnowwolf/lede
  MY_URL: https://github.com/haiibo/openwrt-packages
  REPO_BRANCH: master
  HOST_NAME: DinG
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: firmware/Generic
  COMMIT_LOG_NUM: 1
  DEVICE_NAME: X86
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  RECENT_LASTEST: 15
  TZ: Asia/Shanghai

permissions: write-all

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout OpenWRT
      uses: actions/checkout@v3 

    - name: Initialization Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`  
        sudo -E rm -rf $(curl -sSL ${{ secrets.UBUNTU_DEPENDS }} | sed -n '1p' | tr ' ' '\n')
        sudo -E apt-mark hold grub-efi-amd64-signed
        sudo -E apt update
        sudo -E apt -y purge $(curl -sSL ${{ secrets.UBUNTU_DEPENDS }} | sed -n '2p' | tr ' ' '\n')
        sudo -E apt -y full-upgrade
        sudo -E apt -y install $(curl -sSL ${{ secrets.UBUNTU_DEPENDS }} | sed -n '3p' | tr ' ' '\n')
        sudo -E systemctl daemon-reload
        sudo -E apt -y autoremove --purge
        sudo -E apt clean
        sudo -E apt -y autoclean
        sudo -E timedatectl set-timezone "$TZ"
        export BUILD_DATE=$(TZ=UTC-8 date +"%y.%m.%d_%H.%M.%S")
        echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV
        echo "DEVICE_NAME=$DEVICE_NAME" >> $GITHUB_ENV

    - name: Clone LEDE Code
      run: |
        git clone --depth=1 --single-branch $REPO_URL
        cd ./lede 
        sed -i "1i src-git haibo $MY_URL" $FEEDS_CONF
        cat feeds.conf.default
        tree
        
    - name: update install Feeds
      run: |
        cd ./lede && ./scripts/feeds update -a && ./scripts/feeds install -a

    - name: Load custom build
      run: |
        cd ./lede 
        rm -rf ./tmp && rm -rf ./.config*
        sh <(curl -Ls ${{ secrets.DIY_P1_SH }}) diy ${{ github.event.inputs.device }} ${{ github.event.inputs.host }} ${{ github.event.inputs.ip }} ${{ github.event.inputs.core }}
        cat .config
        make defconfig

    - name: Download Packages
      run: cd ./lede && make -j16 download

    - name: Compile Firmware
      run: |
        cd ./lede
        make -j$(nproc) || make -j1 V=s
        echo "======================="
        df -h
        echo "======================="
        du -h --max-depth=1 ./build_dir
        echo "======================="
        du -h --max-depth=1 ./bin
        echo "=======================" 
        
    - name: file organization
      run: |
        find ./lede/bin/targets/ -type f ! \( -name "*.bin" -o -name "*.img.gz" -o -name "*.vmdk" \) -delete
        find ./lede/bin/targets/* -type f -name "*.*" -print0 | xargs -0 -I{} mv {} ./lede/bin/targets/
        cp -rf ./lede/.config ./lede/bin/targets/config.buildinfo
        tree ./lede/bin/targets/
        
    - name: Release Firmware
      uses: softprops/action-gh-release@v1
      with:
        tag_name: OpenWRT_Firmware_${{env.BUILD_DATE}}
        files: ./lede/bin/targets/*.*
        body: |
          LEDE OpenWrt ${{ env.DEVICE_NAME }} 固件 
          * 【Default】内核版本: 6.1.22 Plus
          * 【Default】主题: Argon
          * 【Default】IP: ${{ github.event.inputs.ip }}
          * 【Default】username: root
          * 【Default】password: password
          * 【Default】增加: iStore应用商店丨iStore首页丨iStore网络向导 
          * 【Default】科学网插件: PassWall科学上网丨丨Hello World科学上网
          * 【Default】科学网插件:OpenClash小猫咪科学上网丨SSR Plus+科学上网丨Bypass科学上网
          * 【Default】增加: NANO编辑器
    - name: Delete Old Releases
      uses: dev-drprasad/delete-older-releases@v0.2.1
      with:
        keep_latest: 3
        delete_tags: true

    - name: Delete Old Workflows
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 1
        keep_minimum_runs: 3           
