#=================================================
# OpenWRT-CI Workflows for Build OpenWRT firmware
# openwrt:LEDE
# package:haiibo
#=================================================

name: Build_OpenWRT

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  REPO_URL: https://github.com/coolsnowwolf/lede
  MY_URL: https://github.com/haiibo/openwrt-packages
  REPO_BRANCH: master
  HOST_NAME: DinG
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: firmware/Generic
  DIY_P1_SH: bash/diy-scripts.sh
  COMMIT_LOG_NUM: 1
  DEVICE_NAME: X86
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  RECENT_LASTEST: 15
  TZ: Asia/Shanghai

permissions: write-all

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout OpenWRT
      uses: actions/checkout@v3 

    - name: Initialization Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
        sudo -E apt-mark hold grub-efi-amd64-signed
        sudo -E apt update
        sudo -E apt -y purge azure-cli* docker* ghc* zulu* llvm* firefox google* dotnet* powershell* openjdk* mysql* php* mongodb* dotnet* moby* snap*
        sudo -E apt -y full-upgrade
        sudo -E apt -y install $(curl -fsSL https://github.com/Joshua-DinG/openwrt/raw/main/depends-ubuntu)
        sudo -E systemctl daemon-reload
        sudo -E apt -y autoremove --purge
        sudo -E apt clean
        sudo -E timedatectl set-timezone "$TZ"
        export BUILD_DATE=$(TZ=UTC-8 date +"%y.%m.%d_%H.%M.%S")
        echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV
        echo "DEVICE_NAME=$DEVICE_NAME" >> $GITHUB_ENV

    - name: Clone LEDE Code
      run: |
        git clone --depth=1 --single-branch $REPO_URL
        cd ./lede 
        sed -i "1i src-git haibo $MY_URL" $FEEDS_CONF
        cat feeds.conf.default
        
    - name: update install Feeds
      run: |
        cd ./lede && ./scripts/feeds update -a && ./scripts/feeds install -a

    - name: Load Custom Configuration
      run: |
        chmod +x $DIY_P1_SH; cd ./lede; $GITHUB_WORKSPACE/$DIY_P1_SH

    - name: Load custom build
      run: |
        cd ./lede && rm -rf ./tmp && rm -rf ./.config*
        cat $GITHUB_WORKSPACE/$CONFIG_FILE > .config
        make defconfig

    - name: Download Packages
      run: cd ./lede && make -j16 download

    - name: Compile Firmware
      run: |
        cd ./lede
        make -j$(nproc) || make -j1 V=s
        echo "======================="
        df -h
        echo "======================="
        du -h --max-depth=1 ./build_dir
        echo "======================="
        du -h --max-depth=1 ./bin
        echo "=======================" 
        
    - name: file organization
      run: |
        find ./lede/bin/targets/ -type f ! \( -name "*.bin" -o -name "*.img.gz" -o -name "*.vmdk" \) -delete
        cp -rf ./lede/.config ./lede/bin/targets/config.buildinfo
        
    - name: Release Firmware
      uses: softprops/action-gh-release@v1
      with:
        tag_name: OpenWRT_Firmware_${{env.BUILD_DATE}}
        files: ./lede/bin/targets/*/*/(*.bin|*.img.gz|*.vmdk|*.buildinfo)
        body: |
          LEDE OpenWrt X86固件 ${{ env.DEVICE_NAME }}
          * 【Default】内核版本: 6.1.21
          * 【Default】主题: Argon
          * 【Default】IP: 192.168.2.88
          * 【Default】username: root
          * 【Default】password: password
          * 【Default】增加: iStore应用商店丨iStore首页丨iStore网络向导 
          * 【Default】科学网插件: OpenClash小猫咪科学上网丨PassWall科学上网丨丨Hello World科学上网丨Bypass科学上网丨SSR Plus+科学上网
          * 【Default】增加: NANO编辑器
    - name: Delete Old Releases
      uses: dev-drprasad/delete-older-releases@v0.2.1
      with:
        keep_latest: 3
        delete_tags: true

    - name: Delete Old Workflows
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 1
        keep_minimum_runs: 3           
